// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADEvskZlSa-lOmqhbKXiljmzBmzXR_NVo',
    appId: '1:1074107352890:web:35c8482fe3e67702737203',
    messagingSenderId: '1074107352890',
    projectId: 'menstrualabnormalitydetection',
    authDomain: 'menstrualabnormalitydetection.firebaseapp.com',
    storageBucket: 'menstrualabnormalitydetection.firebasestorage.app',
    measurementId: 'G-MSYNCQYMXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUdK0UAK_0E7y1Fl1fDsRjFCrwVpsYWCk',
    appId: '1:1074107352890:android:280027cd908e1211737203',
    messagingSenderId: '1074107352890',
    projectId: 'menstrualabnormalitydetection',
    storageBucket: 'menstrualabnormalitydetection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJEBKMjZrLdkiUbb2WEmdm1PWPIH4BDnw',
    appId: '1:1074107352890:ios:5243ae5fdb2b6c26737203',
    messagingSenderId: '1074107352890',
    projectId: 'menstrualabnormalitydetection',
    storageBucket: 'menstrualabnormalitydetection.firebasestorage.app',
    iosClientId: '1074107352890-5fnhmb5qoe56seso2j99eina4cckdu6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.menstrualAbnormality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJEBKMjZrLdkiUbb2WEmdm1PWPIH4BDnw',
    appId: '1:1074107352890:ios:5243ae5fdb2b6c26737203',
    messagingSenderId: '1074107352890',
    projectId: 'menstrualabnormalitydetection',
    storageBucket: 'menstrualabnormalitydetection.firebasestorage.app',
    iosClientId: '1074107352890-5fnhmb5qoe56seso2j99eina4cckdu6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.menstrualAbnormality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADEvskZlSa-lOmqhbKXiljmzBmzXR_NVo',
    appId: '1:1074107352890:web:2049d9989d00fafa737203',
    messagingSenderId: '1074107352890',
    projectId: 'menstrualabnormalitydetection',
    authDomain: 'menstrualabnormalitydetection.firebaseapp.com',
    storageBucket: 'menstrualabnormalitydetection.firebasestorage.app',
    measurementId: 'G-TPXFDE3YWT',
  );

}